manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.7.0
      import: true
    # Drivers repository
    - name: air-quality-wing-drivers
      path: aqw
      revision: fa12a3daba02f373a1f55018ad097851492c4c67
      url: https://github.com/circuitdojo/air-quality-wing-zephyr-drivers.git
      import: true
    # Golioth repository.
    - name: golioth
      path: modules/lib/golioth
      revision: 6d9a0df93bbe05a89f6f36404183656f85413602
      url: https://github.com/golioth/zephyr-sdk.git
    # QCBOR
    - name: qcbor
      revision: 3427dee6898da78a509c2259cee65960011d775c
      path: demo/golioth/lib/qcbor
      url: https://github.com/laurencelundblade/QCBOR.git
  self:
    # This repository should be cloned to 
    path: demo