manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.6.1
      import: true
    # Drivers repository
    - name: air-quality-wing-drivers
      path: aqw
      revision: 99c5d79d37240877984442256dd173a114a75a84
      url: https://github.com/circuitdojo/air-quality-wing-zephyr-drivers.git
      import: true
    # Golioth repository.
    - name: golioth
      path: modules/lib/golioth
      revision: b59c21bafc78a57a38b9094cda33c453a8bed38d
      url: https://github.com/golioth/zephyr-sdk.git
    # QCBOR
    - name: qcbor
      revision: 3427dee6898da78a509c2259cee65960011d775c
      path: demo/golioth/lib/qcbor
      url: https://github.com/laurencelundblade/QCBOR.git
  self:
    # This repository should be cloned to 
    path: demo