manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.7.0
      import: true
    # Drivers repository
    - name: air-quality-wing-drivers
      path: aqw
      revision: main
      url: https://github.com/circuitdojo/air-quality-wing-zephyr-drivers.git
      import: true
    # Golioth repository.
    - name: golioth
      path: modules/lib/golioth
      revision: main
      url: https://github.com/golioth/zephyr-sdk.git
      import:
        name-allowlist:
          - qcbor
  self:
    # This repository should be cloned to 
    path: demo