manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.6.1
      import: true
    # Drivers repository
    - name: air-quality-wing-drivers
      path: aqw
      revision: main
      url: git@github.com:circuitdojo/air-quality-wing-zephyr-drivers.git
  self:
    # This repository should be cloned to 
    path: demo