name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: demo

      - name: Initialize
        working-directory: demo
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: demo
        run: |
          ./scripts/build_all.sh

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: demo/_out/